### PR TITLE
Create account bugs

### LINKED ISSUE #46: [Frontend] User not redirected after signing up
Suggestion:
- Sign up should redirect user to login page
- A back button to direct user back to login page should be implemented on the sign up page

### PR DESCRIPTION
**Pull request by thanwinnikki**
Fixes #46

### CODE REVIEW

File: frontend/src/hooks/useSignUp.js [hunk 1]
```diff
@@ -36,9 +38,9 @@ const useSignUp = () => {
           setLoading(false);
         } else {
```
Comment (jaredlhf) [inline frontend/src/hooks/useSignUp.js:39]: I feel that the if else block here might not be necessary as the error message can be propagated from the backend. Any thoughts?

Comment (Ziyang-98) [reply frontend/src/hooks/useSignUp.js:39]: I think it is okay. Error message from the backend might not be user friendly so it is okay to detect status and send appropriate message. On that note, the message could be better suited for the user as user might not know what "backend" is. For instance, the message could be "Encountered issues connecting to server. Check if your connection is stable?"

File: frontend/src/components/SignUpSuccessDialog/index.js [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+import DialogContent from "@mui/material/DialogContent";
+import DialogContentText from "@mui/material/DialogContentText";
+import DialogTitle from "@mui/material/DialogTitle";
+import { styles } from "./styles";
+
+export default function SuccessSignInDialog(isSignupSuccess) {
+  const [open, setOpen] = useState(true);
+  const navigate = useNavigate();
+
+  const handleCloseDialog = () => {
```
Comment (Ziyang-98) [inline frontend/src/components/SignUpSuccessDialog/index.js:15]: Since this is working already, can remove` console.log`s and `navigate("#", { replace: true });` from `useSignup::handleSignUpSuccess`

**Review by Ziyang-98 — COMMENTED** [review]
I added some comments for the PR. Lmk if you need more details!

**Review by Ziyang-98 — APPROVED** [review]
LGTM!
